// Generated by Takahe v0.1.0
// Target: sky130_fd_sc_hd

module dozenal_alu (
    output carry,
    input  cin,
    output cout,
    input  op,
    output carry_out,
    output zero,
    input  [3:0] a,
    output [3:0] y,
    input  [3:0] b,
    output [3:0] sum,
    output [15:0] result
);

wire tmp;
wire tk_const;
wire d_and;
wire d_or;
wire d_not;
wire d_sum;
wire d_carry;

wire sel;
wire const_0;
wire const_1;
wire const_2;
wire const_3;
wire tmp_0;
wire tmp_1;
wire tmp_2;
wire tmp_3;
wire c1_2_0;
wire nb_2_0;
wire xb_2_0;
wire ab_2_0;
wire cx_2_0;
wire cy_2_0;
wire nb_2_1;
wire xb_2_1;
wire ab_2_1;
wire cx_2_1;
wire cy_2_1;
wire nb_2_2;
wire xb_2_2;
wire ab_2_2;
wire cx_2_2;
wire cy_2_2;
wire nb_2_3;
wire xb_2_3;
wire ab_2_3;
wire cx_2_3;
wire cy_2_3;
wire cat_0;
wire cat_1;
wire cat_2;
wire cat_3;
wire cat_4;
wire tmp_4;
wire xb_14_0;
wire cy_14_0;
wire xb_14_1;
wire ab_14_1;
wire cx_14_1;
wire cy_14_1;
wire xb_14_2;
wire ab_14_2;
wire cx_14_2;
wire cy_14_2;
wire xb_14_3;
wire ab_14_3;
wire cx_14_3;
wire cy_14_3;
wire xb_14_4;
wire ab_14_4;
wire cx_14_4;
wire cy_14_4;
wire total_0;
wire total_1;
wire total_2;
wire total_3;
wire total_4;
wire const_4;
wire sel_0;
wire sel_1;
wire sel_2;
wire sel_3;
wire c1_21_0;
wire nb_21_0;
wire xb_21_0;
wire ab_21_0;
wire cx_21_0;
wire cy_21_0;
wire nb_21_1;
wire xb_21_1;
wire ab_21_1;
wire cx_21_1;
wire cy_21_1;
wire nb_21_2;
wire xb_21_2;
wire ab_21_2;
wire cx_21_2;
wire cy_21_2;
wire nb_21_3;
wire xb_21_3;
wire ab_21_3;
wire cx_21_3;
wire cy_21_3;
wire xb_29_0;
wire cy_29_0;
wire xb_29_1;
wire ab_29_1;
wire cx_29_1;
wire cy_29_1;
wire xb_29_2;
wire ab_29_2;
wire cx_29_2;
wire cy_29_2;
wire xb_29_3;
wire ab_29_3;
wire cx_29_3;
wire cy_29_3;
wire xb_29_4;
wire ab_29_4;
wire cx_29_4;
wire cy_29_4;
wire xb_32_0;
wire cy_32_0;
wire xb_32_1;
wire ab_32_1;
wire cx_32_1;
wire cy_32_1;
wire xb_32_2;
wire ab_32_2;
wire cx_32_2;
wire cy_32_2;
wire xb_32_3;
wire ab_32_3;
wire cx_32_3;
wire cy_32_3;
wire xb_32_4;
wire ab_32_4;
wire cx_32_4;
wire cy_32_4;
wire c1_39_0;
wire nb_39_0;
wire xb_39_0;
wire ab_39_0;
wire cx_39_0;
wire cy_39_0;
wire nb_39_1;
wire xb_39_1;
wire ab_39_1;
wire cx_39_1;
wire cy_39_1;
wire nb_39_2;
wire xb_39_2;
wire ab_39_2;
wire cx_39_2;
wire cy_39_2;
wire nb_39_3;
wire xb_39_3;
wire ab_39_3;
wire cx_39_3;
wire cy_39_3;
wire const_5;
wire const_6;
wire const_7;
wire const_8;
wire const_9;
wire const_10;
wire const_11;
wire const_12;
wire const_13;
wire const_14;
wire const_15;
wire ei;
wire e1;

// UNMAPPED: GE w=1
sky130_fd_sc_hd__buf_1 U0 ( .A(tmp), .X(carry) );
// UNMAPPED: GE w=1
sky130_fd_sc_hd__buf_1 U1 ( .A(tmp), .X(cout) );
assign carry_out = 1'b0;
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
sky130_fd_sc_hd__buf_1 U3 ( .A(sel), .X(carry_out) );
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
sky130_fd_sc_hd__buf_1 U4 ( .A(sel), .X(carry_out) );
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: SELECT w=1
// UNMAPPED: EQ w=1
sky130_fd_sc_hd__buf_1 U5 ( .A(tmp), .X(zero) );
sky130_fd_sc_hd__xor2_1 U6 ( .A(xb_2_0), .B(c1_2_0), .X(tmp_0) );
sky130_fd_sc_hd__xor2_1 U7 ( .A(xb_2_2), .B(cy_2_1), .X(tmp_2) );
sky130_fd_sc_hd__buf_1 U8 ( .A(tmp_0), .X(y[0]) );
sky130_fd_sc_hd__buf_1 U9 ( .A(tmp_1), .X(y[1]) );
sky130_fd_sc_hd__buf_1 U10 ( .A(tmp_2), .X(y[2]) );
sky130_fd_sc_hd__buf_1 U11 ( .A(tmp_3), .X(y[3]) );
sky130_fd_sc_hd__buf_1 U12 ( .A(tmp_0), .X(y[0]) );
sky130_fd_sc_hd__buf_1 U13 ( .A(tmp_1), .X(y[1]) );
sky130_fd_sc_hd__buf_1 U14 ( .A(tmp_2), .X(y[2]) );
sky130_fd_sc_hd__buf_1 U15 ( .A(tmp_3), .X(y[3]) );
sky130_fd_sc_hd__buf_1 U16 ( .A(tmp_0), .X(y[0]) );
sky130_fd_sc_hd__buf_1 U17 ( .A(tmp_1), .X(y[1]) );
sky130_fd_sc_hd__buf_1 U18 ( .A(tmp_2), .X(y[2]) );
sky130_fd_sc_hd__buf_1 U19 ( .A(tmp_3), .X(y[3]) );
sky130_fd_sc_hd__buf_1 U20 ( .A(a[0]), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U21 ( .A(a[1]), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U22 ( .A(a[2]), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U23 ( .A(b[0]), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U24 ( .A(b[1]), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U25 ( .A(b[2]), .X(cat_3) );
assign cy_14_0 = 1'b0;
sky130_fd_sc_hd__xor2_1 U27 ( .A(cat_1), .B(cat_1), .X(xb_14_1) );
sky130_fd_sc_hd__xor2_1 U28 ( .A(xb_14_1), .B(cy_14_0), .X(tmp_1) );
sky130_fd_sc_hd__and2_0 U29 ( .A(cat_1), .B(cat_1), .X(ab_14_1) );
assign cx_14_1 = 1'b0;
sky130_fd_sc_hd__or2_0 U31 ( .A(ab_14_1), .B(cx_14_1), .X(cy_14_1) );
sky130_fd_sc_hd__xor2_1 U32 ( .A(cat_2), .B(cat_2), .X(xb_14_2) );
sky130_fd_sc_hd__xor2_1 U33 ( .A(xb_14_2), .B(cy_14_1), .X(tmp_2) );
sky130_fd_sc_hd__and2_0 U34 ( .A(cat_2), .B(cat_2), .X(ab_14_2) );
sky130_fd_sc_hd__and2_0 U35 ( .A(cy_14_1), .B(xb_14_2), .X(cx_14_2) );
sky130_fd_sc_hd__or2_0 U36 ( .A(ab_14_2), .B(cx_14_2), .X(cy_14_2) );
sky130_fd_sc_hd__xor2_1 U37 ( .A(cat_3), .B(cat_3), .X(xb_14_3) );
sky130_fd_sc_hd__xor2_1 U38 ( .A(xb_14_3), .B(cy_14_2), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U39 ( .A(tmp_1), .X(total_1) );
sky130_fd_sc_hd__buf_1 U40 ( .A(tmp_2), .X(total_2) );
sky130_fd_sc_hd__buf_1 U41 ( .A(tmp_3), .X(total_3) );
sky130_fd_sc_hd__buf_1 U42 ( .A(total_3), .X(sel_3) );
sky130_fd_sc_hd__xor2_1 U43 ( .A(xb_21_1), .B(cy_21_0), .X(tmp_1) );
assign ab_21_2 = 1'b0;
sky130_fd_sc_hd__and2_0 U45 ( .A(cy_21_1), .B(xb_21_2), .X(cx_21_2) );
sky130_fd_sc_hd__or2_0 U46 ( .A(ab_21_2), .B(cx_21_2), .X(cy_21_2) );
assign nb_21_3 = 1'b0;
sky130_fd_sc_hd__xor2_1 U48 ( .A(sel_3), .B(nb_21_3), .X(xb_21_3) );
sky130_fd_sc_hd__xor2_1 U49 ( .A(xb_21_3), .B(cy_21_2), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U50 ( .A(total_1), .X(sel_1) );
sky130_fd_sc_hd__buf_1 U51 ( .A(total_2), .X(sel_2) );
sky130_fd_sc_hd__buf_1 U52 ( .A(total_3), .X(sel_3) );
sky130_fd_sc_hd__mux2_1 U53 ( .A0(sel_1), .A1(tmp_1), .S(carry), .X(tmp_1) );
sky130_fd_sc_hd__mux2_1 U54 ( .A0(sel_2), .A1(tmp_2), .S(carry), .X(tmp_2) );
sky130_fd_sc_hd__mux2_1 U55 ( .A0(sel_3), .A1(tmp_3), .S(carry), .X(tmp_3) );
assign sum[0] = 1'b0;
sky130_fd_sc_hd__buf_1 U57 ( .A(tmp_1), .X(sum[1]) );
sky130_fd_sc_hd__buf_1 U58 ( .A(tmp_2), .X(sum[2]) );
sky130_fd_sc_hd__buf_1 U59 ( .A(tmp_3), .X(sum[3]) );
sky130_fd_sc_hd__buf_1 U60 ( .A(a[2]), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U61 ( .A(b[2]), .X(cat_3) );
sky130_fd_sc_hd__and2_0 U62 ( .A(cat_2), .B(cat_2), .X(ab_29_2) );
sky130_fd_sc_hd__and2_0 U63 ( .A(cy_29_1), .B(xb_29_2), .X(cx_29_2) );
sky130_fd_sc_hd__or2_0 U64 ( .A(ab_29_2), .B(cx_29_2), .X(cy_29_2) );
sky130_fd_sc_hd__xor2_1 U65 ( .A(cat_3), .B(cat_3), .X(xb_29_3) );
sky130_fd_sc_hd__xor2_1 U66 ( .A(xb_29_3), .B(cy_29_2), .X(tmp_3) );
assign cat_3 = 1'b0;
assign cy_32_2 = 1'b0;
sky130_fd_sc_hd__xor2_1 U69 ( .A(tmp_3), .B(cat_3), .X(xb_32_3) );
sky130_fd_sc_hd__xor2_1 U70 ( .A(xb_32_3), .B(cy_32_2), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U71 ( .A(tmp_3), .X(total_3) );
sky130_fd_sc_hd__buf_1 U72 ( .A(total_1), .X(sel_1) );
sky130_fd_sc_hd__buf_1 U73 ( .A(total_2), .X(sel_2) );
sky130_fd_sc_hd__buf_1 U74 ( .A(total_3), .X(sel_3) );
assign cy_39_0 = 1'b1;
assign nb_39_1 = 1'b1;
sky130_fd_sc_hd__xor2_1 U77 ( .A(sel_1), .B(nb_39_1), .X(xb_39_1) );
sky130_fd_sc_hd__xor2_1 U78 ( .A(xb_39_1), .B(cy_39_0), .X(tmp_1) );
sky130_fd_sc_hd__and2_0 U79 ( .A(sel_1), .B(nb_39_1), .X(ab_39_1) );
sky130_fd_sc_hd__and2_0 U80 ( .A(cy_39_0), .B(xb_39_1), .X(cx_39_1) );
sky130_fd_sc_hd__or2_0 U81 ( .A(ab_39_1), .B(cx_39_1), .X(cy_39_1) );
assign nb_39_2 = 1'b0;
sky130_fd_sc_hd__xor2_1 U83 ( .A(sel_2), .B(nb_39_2), .X(xb_39_2) );
sky130_fd_sc_hd__xor2_1 U84 ( .A(xb_39_2), .B(cy_39_1), .X(tmp_2) );
assign ab_39_2 = 1'b0;
sky130_fd_sc_hd__and2_0 U86 ( .A(cy_39_1), .B(xb_39_2), .X(cx_39_2) );
sky130_fd_sc_hd__or2_0 U87 ( .A(ab_39_2), .B(cx_39_2), .X(cy_39_2) );
assign nb_39_3 = 1'b0;
sky130_fd_sc_hd__xor2_1 U89 ( .A(sel_3), .B(nb_39_3), .X(xb_39_3) );
sky130_fd_sc_hd__xor2_1 U90 ( .A(xb_39_3), .B(cy_39_2), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U91 ( .A(total_1), .X(sel_1) );
sky130_fd_sc_hd__buf_1 U92 ( .A(total_2), .X(sel_2) );
sky130_fd_sc_hd__buf_1 U93 ( .A(total_3), .X(sel_3) );
sky130_fd_sc_hd__mux2_1 U94 ( .A0(sel_1), .A1(tmp_1), .S(cout), .X(tmp_1) );
sky130_fd_sc_hd__mux2_1 U95 ( .A0(sel_2), .A1(tmp_2), .S(cout), .X(tmp_2) );
sky130_fd_sc_hd__mux2_1 U96 ( .A0(sel_3), .A1(tmp_3), .S(cout), .X(tmp_3) );
assign sum[0] = 1'b0;
sky130_fd_sc_hd__buf_1 U98 ( .A(tmp_1), .X(sum[1]) );
sky130_fd_sc_hd__buf_1 U99 ( .A(tmp_2), .X(sum[2]) );
sky130_fd_sc_hd__buf_1 U100 ( .A(tmp_3), .X(sum[3]) );
sky130_fd_sc_hd__buf_1 U101 ( .A(sel), .X(cat_0) );
sky130_fd_sc_hd__buf_1 U102 ( .A(sel), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U103 ( .A(sel), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U104 ( .A(sel), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U105 ( .A(cat_0), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U106 ( .A(cat_1), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U107 ( .A(cat_2), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U108 ( .A(cat_3), .X(result[3]) );
sky130_fd_sc_hd__buf_1 U109 ( .A(sel), .X(cat_0) );
sky130_fd_sc_hd__buf_1 U110 ( .A(sel), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U111 ( .A(sel), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U112 ( .A(sel), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U113 ( .A(cat_0), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U114 ( .A(cat_1), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U115 ( .A(cat_2), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U116 ( .A(cat_3), .X(result[3]) );
sky130_fd_sc_hd__buf_1 U117 ( .A(sel), .X(cat_0) );
sky130_fd_sc_hd__buf_1 U118 ( .A(sel), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U119 ( .A(sel), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U120 ( .A(sel), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U121 ( .A(cat_0), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U122 ( .A(cat_1), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U123 ( .A(cat_2), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U124 ( .A(cat_3), .X(result[3]) );
sky130_fd_sc_hd__buf_1 U125 ( .A(sel), .X(cat_0) );
sky130_fd_sc_hd__buf_1 U126 ( .A(sel), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U127 ( .A(sel), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U128 ( .A(sel), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U129 ( .A(cat_0), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U130 ( .A(cat_1), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U131 ( .A(cat_2), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U132 ( .A(cat_3), .X(result[3]) );
sky130_fd_sc_hd__buf_1 U133 ( .A(sel), .X(cat_0) );
sky130_fd_sc_hd__buf_1 U134 ( .A(sel), .X(cat_1) );
sky130_fd_sc_hd__buf_1 U135 ( .A(sel), .X(cat_2) );
sky130_fd_sc_hd__buf_1 U136 ( .A(sel), .X(cat_3) );
sky130_fd_sc_hd__buf_1 U137 ( .A(cat_0), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U138 ( .A(cat_1), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U139 ( .A(cat_2), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U140 ( .A(cat_3), .X(result[3]) );
sky130_fd_sc_hd__buf_1 U141 ( .A(a[0]), .X(result[0]) );
sky130_fd_sc_hd__buf_1 U142 ( .A(a[1]), .X(result[1]) );
sky130_fd_sc_hd__buf_1 U143 ( .A(a[2]), .X(result[2]) );
sky130_fd_sc_hd__buf_1 U144 ( .A(a[3]), .X(result[3]) );
sky130_fd_sc_hd__clkinv_1 U145 ( .A(a[1]), .Y(ei) );
sky130_fd_sc_hd__buf_1 U146 ( .A(ei), .X(tmp_1) );
sky130_fd_sc_hd__buf_1 U147 ( .A(a[3]), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U148 ( .A(b[0]), .X(tmp_0) );
sky130_fd_sc_hd__buf_1 U149 ( .A(b[1]), .X(tmp_1) );
sky130_fd_sc_hd__buf_1 U150 ( .A(b[2]), .X(tmp_2) );
sky130_fd_sc_hd__buf_1 U151 ( .A(b[3]), .X(tmp_3) );
sky130_fd_sc_hd__buf_1 U152 ( .A(b[0]), .X(tmp_0) );
sky130_fd_sc_hd__buf_1 U153 ( .A(b[1]), .X(tmp_1) );
sky130_fd_sc_hd__buf_1 U154 ( .A(b[2]), .X(tmp_2) );
sky130_fd_sc_hd__buf_1 U155 ( .A(b[3]), .X(tmp_3) );
assign tmp_2 = 1'b1;

endmodule
